# Generated by Django 3.1.4 on 2020-12-18 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 18, 11, 43, 36, 570926, tzinfo=utc)),
        ),
    ]
