# Generated by Django 3.1.4 on 2020-12-18 12:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_blog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 12, 18, 12, 31, 28, 144438, tzinfo=utc)),
        ),
    ]
